# netlify.toml

[build]
  publish = "dist/client"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://api.hermidamaia.adv.br/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
